backend_srcdir = src/backend

PERF_BACKEND_SRCS = \
		    $(backend_srcdir)/perf.c \
		    $(backend_srcdir)/perf-handler.c

FTRACE_BACKEND_SRCS = $(backend_srcdir)/ftrace.c \
		      $(backend_srcdir)/ftrace-handler.c

BACKEND_SRCS = $(PERF_BACKEND_SRCS) $(FTRACE_BACKEND_SRCS)
