backend_srcdir = src/backend

PERF_BACKEND_SRCS = \
		    $(backend_srcdir)/perf.c \
		    $(backend_srcdir)/perf-sys.c\
		    $(backend_srcdir)/perf-events.c

FTRACE_BACKEND_SRCS = $(backend_srcdir)/ftrace.c

BACKEND_SRCS = $(PERF_BACKEND_SRCS) $(FTRACE_BACKEND_SRCS)
